---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jira
  name: jira
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jira
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jira
  name: jira
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: jira
      name: jira
    spec:
      containers:
        - name: jira
          image: "gcr.io/hightowerlabs/jira:7.3.6-standalone"
          resources:
            requests:
              cpu: "1"
              memory: "2G"
          volumeMounts:
            - name: "jira-home"
              mountPath: /opt/jira-home
      volumes:
        - name: jira-home
          persistentVolumeClaim:
            claimName: jira-test-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-test-1
spec:
  storageClassName: nfs-provisioner-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3G
