apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-test
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "nfs-disk"
      - name: ReplicaCount
        value: "2"       
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete