apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: nfs-disk
spec:
  name: nfs-disk
  type: disk
  poolSpec:
    poolType: striped
  # NOTE - Appropriate disks need to be fetched using `kubectl get disks`
  #
  # `Disk` is a custom resource supported by OpenEBS with `node-disk-manager`
  # as the disk operator
# Replace the following with actual disk CRs from your cluster `kubectl get disks`
# Uncomment the below lines after updating the actual disk names.
  disks:
    diskList:
      - disk-1
      - disk-2
      - disk-3
      - disk-4
      - disk-5
      - disk-6